config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#home"

  namespace :admin do
    get "/", to: redirect("/admin/startups")

    resources :startups, :pages, :posts

    get "homepage" => "homepage#index", as: :homepage_edit
    post "homepage" => "homepage#update"
  end

  get "/blog" => "posts#index"
  get "/blog/:slug" => "posts#show", as: :blog_post
  get ":slug" => "pages#show"
end

app/models/metadata.rb
class Metadata < ActiveRecord::Base

  def self.get(key)
    data = where(key: key).first
    data = self.set(key, "") unless data
    data.value
  end

  def self.set(key, value)
    data = where(key: key).first_or_create
    data.update(value: value)
    data
  end

  def self.get_group key
    group = {}
    self.send(key).each do |field|
      group[field] = self.get(field)
    end

    group

  rescue NoMethodError => e
    {}
  end

  def self.set_group key, params
    self.send(key).each do |field|
      self.set(field, params[field])
    end

  rescue NoMethodError => e
    raise GroupNotFound, "No group for key #{key}"
  end

  class GroupNotFound < StandardError
  end

  private

    def self.homepage_group
      %w[homepage_header_content homepage_footer_content contact_email twitter_username]
    end

end

app/models/page.rb
class Page < ActiveRecord::Base

  validates_presence_of :title, :slug, :content
  validates_uniqueness_of :slug, on: :create

  def self.get_by_slug slug
    where(slug: slug).first
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :title, :slug, :extract, :content, :status
  validates :slug, uniqueness: {case_sensitive: false}, slug: true, on: :create

  def self.published
    where(status: 'published').order(id: :desc)
  end

  def self.get_by_slug slug, published_only = true
    q = where(slug: slug)
    q = q.where(status: 'published') if published_only

    q.first
  end

  def nice_date
    created_at.strftime("%A, %d %B %Y, %H:%M")
  end

  def next
    @next_post ||= self.class.where(status: 'published').where("id > ?", id).order(id: :asc).first
  end

  def prev
    @prev_post ||= self.class.where(status: 'published').where("id < ?", id).order(id: :desc).first
  end

end

app/models/startup.rb
class Startup < ActiveRecord::Base

  validates_presence_of :name, :year_founded, :url, :status

  has_attached_file :uploaded_logo,
    styles: { standard: "500x500" },
    default_url: "default.jpg",
    path: "images/:style/:id_:filename",
    preserve_files: true

  validates_attachment_content_type :uploaded_logo, content_type: /\Aimage\/.*\Z/
  # validates_attachment_presence :uploaded_logo


  def self.get_active
    where(status: 'active')
  end

end

app/models/typeform_api.rb
require "json"

class TypeformApi
  attr_reader :uid, :api_key

  def initialize(uid = nil, api_key = nil)
    @uid = uid || ENV.fetch("TYPEFORM_UID")
    @api_key = api_key || ENV.fetch("TYPEFORM_ACCESS_TOKEN")
  end

  def fetch_new_startups
    res = HTTP.auth("Bearer #{api_key}")
              .get(endpoint, params: { since: last_check, completed: true })
    res = JSON.parse(res.body.to_s, symbolize_names: true)

    startups = res[:items].map do |startup|
      startup[:answers].inject({}) do |memo, answer|
        field_name = question_ids_map[answer[:field][:id]]
        field_value = answer[answer[:type].to_sym]
        memo[field_name] = field_value
        memo
      end
    end

    Metadata.set('typeform_checked_at', Time.now.to_i)

    startups
  end

  private

  def last_check
    Metadata.get('typeform_checked_at').presence
  end

  def endpoint
    "https://api.typeform.com/forms/#{uid}/responses"
  end

  def question_ids_map
    @question_ids_map ||= JSON.parse(ENV.fetch("TYPEFORM_FIELD_IDS_TO_NAMES"))
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

end

app/controllers/admin/base_controller.rb
module Admin
	class BaseController < ApplicationController

		before_action :authenticate_user!

		layout "admin"
	
	end
end

app/controllers/admin/dashboard_controller.rb
module Admin
	class DashboardController < BaseController

		def index
			
		end

	end
end

app/controllers/admin/homepage_controller.rb
module Admin
  class HomepageController < BaseController

    def index
      @homepage = Metadata.get_group 'homepage_group'
    end

    def update
      Metadata.set_group 'homepage_group', params
      redirect_to admin_homepage_edit_path, notice: 'Homepage content has been updated'
    end

  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < BaseController
    before_action :set_page, only: [:edit, :update, :destroy]

    def index
      @pages = Page.all
    end

    def new
      @page = Page.new
    end

    def create
      @page = Page.new(page_params)

      if @page.save
        redirect_to edit_admin_page_path(@page), notice: "New page has been created"
      else
        flash[:error] = "There were some errors creating the page"
        render :new
      end
    end

    def edit
    end

    def update
      if @page.update(page_params)
        redirect_to edit_admin_page_path(@page), notice: "Page has been updated"
      else
        flash[:error] = "There were some errors updating the page"
        render :edit
      end
    end

    def destroy
      @page.destroy!
      redirect_to admin_pages_path, notice: 'Page has been deleted'
    end

    private

      def set_page
        @page = Page.find(params[:id])
      end

      def page_params
        params.require(:page).permit(:title, :slug, :content)
      end

  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    before_action :set_post, only: [:edit, :update, :destroy]


    def index
      @posts = Post.all
    end

    def new
      @post = Post.new
    end

    def create
      @post = current_user.posts.new(post_params)

      if @post.save
        redirect_to edit_admin_post_path(@post), notice: "New post has been created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to edit_admin_post_path(@post), notice: "Post has been updated"
      else
        flash[:error] = "There were some errors updating the post"
        render :edit
      end
    end

    def destroy
      @post.destroy!
      redirect_to admin_posts_path, notice: 'Post has been deleted'
    end

    private

     def set_post
      @post = Post.find(params[:id])
     end

     def post_params
      params.require(:post).permit(:title, :slug, :extract, :content, :status)
     end

  end
end

app/controllers/admin/startups_controller.rb
module Admin
  class StartupsController < BaseController
    before_action :set_startup, only: [:edit, :update, :destroy]

    def index
      @startups = Startup.all
    end

    def edit
    end

    def show
      redirect_to edit_admin_startup_path params[:id]
    end

    def update
      if @startup.update(startup_params)
        redirect_to edit_admin_startup_path(@startup), notice: 'Startup was updated'
      else
        render :edit
      end
    end

    def destroy
      @startup.destroy!
      redirect_to admin_startups_path, notice: 'Startup has been deleted'
    end

    private

    def set_startup
      @startup = Startup.find(params[:id])
    end

    def startup_params
      params.require(:startup).permit(:name, :year_founded, :location, :description, :url, :twitter, :uploaded_logo, :status)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
    @startups = Startup.get_active
    @homepage = Metadata.get_group 'homepage_group'
	end

  def show
    @page = Page.get_by_slug(params[:slug])
    raise ActionController::RoutingError.new('Not Found') unless @page

    render 'default'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.published
  end

  def show
    @post = Post.get_by_slug(params[:slug])
    raise ActionController::RoutingError.new('Not Found') unless @post
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sanitize_helper.rb
module SanitizeHelper
  def sanitize_html(html)
    Sanitize.fragment(html, Sanitize::Config.merge(Sanitize::Config::BASIC,
      elements: ['h2', 'h3', 'h4', 'a', 'p', 'strong', 'em', 'ul', 'ol', 'li']
    )).html_safe
  end
end

app/views/admin/homepage/index.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">General Settings</h2>
</div>
<hr>


<%= form_with(url: admin_homepage_edit_path, class: "mw7") do |f| %>
  <% @homepage.each do |key, val| %>
    <div class="mb4">
      <label class="db mb2"><%= key.humanize %></label>
      <% if key.match?(/_content\z/) %>
        <textarea name="<%= key %>" class="wysiwyg"><%= val %></textarea>
      <% else %>
        <input type="text" name="<%= key %>" value="<%= val %>">
      <% end %>
    </div>
  <% end %>

  <%= f.submit "Save Changes", class: "bg-near-black white fw7 pa3 bn br2 pointer mt4 tracked f6 ttu" %>
<% end %>

app/views/admin/pages/_form.html.erb
<%= form_with(model: @page, url: [:admin, @page], class: "mw7") do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <% unless @page.persisted? %>
    <div class="form-group">
      <%= f.label :slug, "Slug" %>
      <%= f.text_field :slug %>
      <span class="db silver f6 mt3">This cannot be updated after creation</span>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "wysiwyg" %>
  </div>

  <hr>

  <div class="flex items-center mt4">
    <%= f.submit "Save Changes", class: "bg-near-black white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
    <% if @page.persisted? %>
      <%= link_to 'Delete Page', admin_page_path(@page), method: :delete, class: 'delete', "data-confirm" => "Are you sure you want to delete this?", class: "ml7 red" %>
    <% end %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">Edit Page</h2>
  <div class="ml5 self-center">
    <%= link_to "Cancel", admin_pages_path, class: "no-underline bg-light-silver white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<%= render 'form' %>

app/views/admin/pages/index.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">All Pages</h2>
  <div class="ml5 self-center">
    <%= link_to "New Page", new_admin_page_path, class: "no-underline bg-blue white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>


<% if @pages.empty? %>

  <p>No pages have been created yet</p>

<% else %>

  <table cellspacing="0">
    <thead>
      <tr>
        <th>Page Title</th>
        <th>Slug</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.title %></td>
          <td><%= page.slug %></td>
          <td><%= link_to "Edit", edit_admin_page_path(page) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/admin/pages/new.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">New Page</h2>
  <div class="ml5 self-center">
    <%= link_to "Cancel", admin_pages_path, class: "no-underline bg-light-silver white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<%= render 'form' %>

app/views/admin/partials/_head.html.erb
<ul class="admin-nav">
	<li><%= link_to "Startups", admin_startups_path %></li>
  <li><%= link_to "Pages", admin_pages_path %></li>
  <li><%= link_to "Posts", admin_posts_path %></li>
  <li><%= link_to "General Settings", admin_homepage_edit_path %></li>

	<li class="right">
		<p class="tr">Signed in as <%= current_user.email %> | <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></p>
	</li>
</ul>

app/views/admin/posts/_form.html.erb
<%= form_with(model: @post, url: [:admin, @post], class: "mw7") do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <% unless @post.persisted? %>
    <div class="form-group">
      <%= f.label :slug, "Slug (this cannot be updated)" %>
      <%= f.text_field :slug %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :extract %>
    <%= f.text_area :extract %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "wysiwyg" %>
  </div>
  <div class="form-group">
    <%= f.label :status %>
    <%= f.select(:status, ['draft', 'published']) %>
  </div>

  <hr>

  <div class="flex items-center mt4">
    <%= f.submit class: "bg-near-black white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
    <% if @post.persisted? %>
      <%= link_to 'Delete Post', admin_post_path(@post), method: :delete, class: 'delete', "data-confirm" => "Are you sure you want to delete this?", class: "ml7 red" %>
    <% end %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">Edit Blog Post</h2>
  <div class="ml5 self-center">
    <%= link_to "Cancel", admin_posts_path, class: "no-underline bg-light-silver white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<%= render 'form' %>

app/views/admin/posts/index.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">All Blog Posts</h2>
  <div class="ml5 self-center">
    <%= link_to "New Post", new_admin_post_path, class: "no-underline bg-blue white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<% unless @posts.present? %>
  <p>No posts created yet.</p>
<% else %>

  <table cellspacing="0">
    <thead>
      <tr>
        <th>Post Title</th>
        <th>Post Slug</th>
        <th>Status</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.slug %></td>
          <td><%= post.status %></td>
          <td><%= link_to "Edit", edit_admin_post_path(post) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


<% end %>

app/views/admin/posts/new.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">New Blog Post</h2>
  <div class="ml5 self-center">
    <%= link_to "Cancel", admin_posts_path, class: "no-underline bg-light-silver white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<%= render 'form' %>

app/views/admin/startups/edit.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">Edit Startup</h2>
  <div class="ml5 self-center">
    <%= link_to "Cancel", admin_startups_path, class: "no-underline bg-light-silver white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<%= form_with(model: @startup, url: admin_startup_path, method: :put, class: "mw7") do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :year_founded %>
    <%= f.text_field :year_founded %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :url, "Website URL" %>
    <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= f.label :twitter, "Twitter handle" %>
    <%= f.text_field :twitter %>
  </div>
  <div class="form-group flex items-center">
    <div class="flex-auto mr5">
      <%= f.label :uploaded_logo, "Upload Logo" %>
      <%= f.file_field :uploaded_logo %>
      <p>Logo URL: <a href="<%= @startup.logo_url %>" target="_blank"><%= @startup.logo_url %></a></p>
    </div>
    <% if @startup.uploaded_logo_file_name.present? %>
      <div class="bg-dark-green">
        <%= image_tag @startup.uploaded_logo.url(:standard), class: "mw4" %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :status %>
    <%= f.select(:status, ['pending', 'active']) %>
  </div>

  <hr>

  <p>Contact Name: <%= @startup.contact_name %></p>
  <p>Contact Email: <%= mail_to(@startup.contact_email, nil, subject: "Founded in Ireland") %></p>
  <p>Extra Information:<br><%= @startup.extra_info %></p>

  <hr>

  <div class="flex items-center mt4">
    <%= f.submit "Save Changes", class: "bg-near-black white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
    <%= link_to 'Delete Startup', admin_startup_path(@startup), method: :delete, class: 'delete', "data-confirm" => "Are you sure you want to delete this?", class: "ml7 red" %>
  </div>

<% end %>

app/views/admin/startups/index.html.erb
<div class="flex mt5">
  <h2 class="flex-auto ma0">All Startups</h2>
  <div class="ml5 self-center">
    <%#= link_to "New Startup", new_admin_startup_path, class: "no-underline bg-blue white fw7 pa3 bn br2 pointer tracked f6 ttu" %>
  </div>
</div>
<hr>

<% unless @startups.present? %>

  <p>No startups have been added yet</p>

<% else %>

  <table cellspacing="0">
    <thead>
      <tr>
        <th>Startup Name</th>
        <th>Status</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @startups.each do |startup| %>
        <tr>
          <td><%= startup.name %></td>
          <td><%= startup.status %></td>
          <td><%= link_to "Edit", edit_admin_startup_path(startup) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

  <head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# <meta name="description" content="{{ site.description }}"> %>
    <meta name="keywords" content="Ireland, Ireland, Europe, startups, entrepreneurs, innovation" />

    <meta property="og:title" content="Founded in Ireland - The most innovative startups in Ireland" />
    <meta property="og:description" content="Ireland is Europe's hot new startup scene. We list innovative startups with Irish roots." />
    <meta property="og:site_name" content="Founded in Ireland" />
    <meta property="og:image" content="http://foundedinireland.com/static/images/avatar.png" />

    <meta name="twitter:site" content="@foundedireland" />
    <meta name="twitter:title" content="Founded in Ireland - The most innovative startups in Ireland" />

    <meta name="author" content="Alternate Labs" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag 'admin', media: 'all' %>

    <%# <link rel="canonical" href="{{ page.url | replace:'index.html','' | prepend: site.baseurl | prepend: site.url }}"> %>

    <title>Founded In Ireland</title>

    <meta property="og:url" content="http://foundedinireland.com/" />
    <meta property="og:type" content="website" />

    <script>
	    /**
	    * Function that tracks a click on an outbound link in Google Analytics.
	    */
	    var trackOutboundLink = function(url) {
	       ga('send', 'event', 'outbound', 'click', url);
	    }
    </script>

    <%= csrf_meta_tags %>
</head>

<body class="bg-light-gray">
  <%= render "partials/flash_messages" %>

  <% if current_user.present? %>
    <div class="bg-white pa4">
      <div class="mw8 flex items-center center dark-green f6">
        <span class="fw7 mr5 ttu f6 tracked">Admin</span>
        <% link_styles = "no-underline mr5 green f6 fw4 dim" %>
        <%= link_to "Startups", admin_startups_path, class: link_styles %>
        <%= link_to "Pages", admin_pages_path, class: link_styles %>
        <%= link_to "Posts", admin_posts_path, class: link_styles %>
        <%= link_to "General Settings", admin_homepage_edit_path, class: link_styles %>
        <span class="flex-auto tr">
          Signed in as <%= current_user.email %>&nbsp;&nbsp;&nbsp;·&nbsp;&nbsp;&nbsp;
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: link_styles %>
        </span>
      </div>
    </div>
  <% end %>

  <div class="mw8 center mb5">
    <%= yield %>
  </div>

  <%= javascript_include_tag "admin" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# <meta name="description" content="{{ site.description }}"> %>
    <meta name="keywords" content="Ireland, Ireland, Europe, startups, entrepreneurs, innovation" />

    <meta property="og:title" content="Founded in Ireland - The most innovative startups in Ireland" />
    <meta property="og:description" content="Ireland is Europe's hot new startup scene. We list innovative startups with Irish roots." />
    <meta property="og:site_name" content="Founded in Ireland" />
    <meta property="og:image" content="http://foundedinireland.com/static/images/avatar.png" />

    <meta name="twitter:site" content="@foundedireland" />
    <meta name="twitter:title" content="Founded in Ireland - The most innovative startups in Ireland" />

    <meta name="author" content="Alternate Labs" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <title>Founded In Ireland</title>

    <meta property="og:url" content="http://foundedinireland.com/" />
    <meta property="og:type" content="website" />

    <script>
	    /**
	    * Function that tracks a click on an outbound link in Google Analytics.
	    */
	    var trackOutboundLink = function(url) {
	       ga('send', 'event', 'outbound', 'click', url);
	    }
    </script>

    <%= csrf_meta_tags %>
</head>

<body class="frontend">
  <div class="container">

    <%= render "partials/flash_messages" %>

    <header class="page-header clearfix">
      <%= link_to image_tag("fii-logo.png", width: 500, alt: "Founded in Ireland"), root_path, class: "no-link" %>
      <%= yield :header_content %>
    </header>


    <div class="page-content">
      <div class="wrapper">
        <%= yield %>

        <div class="join-box fancy-links">
          <a name="join" class="no-link"></a>
          <%= yield :footer_content %>

          <div>
            <span style="display:inline;"><a class="typeform-share link join-button" href="<%= ENV["TYPEFORM_URL"] %>" data-mode="2" target="_blank">Join&nbsp;the&nbsp;list</a></span>
          </div>
          <br><br>
          <span>Follow on <a href="https://twitter.com/<%= Metadata.get 'twitter_username' %>" target="_blank"><i class="fa fa-twitter-square"></i>&nbsp;Twitter</a>
              &nbsp;&middot;&nbsp; <a class="typeform-share link" href="<%= ENV["TYPEFORM_URL"] %>" data-mode="2" target="_blank">Join&nbsp;the&nbsp;list</a>
              &nbsp;&middot;&nbsp; <a href="mailto:<%= Metadata.get 'contact_email' %>?subject=Founded%20in%20Ireland" target="_blank">Contact</a></span>
        </div>
      </div>
    </div>

    <footer class="page-footer fancy-links">
      <span>All the logos and trademarks used on this website belong to its rightful owner.<br></span>
      <span>This platform is <a href="https://github.com/alternatelabs/founded-in-ireland">Open Source</a> &ndash; built by <a href="https://alternatelabs.co">Alternate Labs</a><br></span>
        <a href="http://foundedx.com" class="no-link" target="_blank">
          <%= image_tag "foundedx-badge.png", alt: "FoundedX" %>
        </a>
    </footer>
  </div>

  <%= javascript_include_tag 'application' %>

  <%# TODO google analytics %>
</body>
</html>

app/views/pages/default.html.erb
<div class="page">

  <h1><%= @page.title %></h1>
  <%= sanitize_html(@page.content) %>

</div>

app/views/pages/home.html.erb
<% content_for :header_content do %>
  <div class="fancy-links">
    <%= @homepage['homepage_header_content'].html_safe %>
  </div>
<% end %>

<ul class="cbp-rfgrid">

  <% @startups.each do |startup| %>
    <li>
      <a href="<%= startup.url %>" target="_blank">
        <%= image_tag startup.uploaded_logo.url(:standard), alt: startup.name %>
        <div>
          <h3><%= startup.name %></h3>
        </div>
      </a>
    </li>
  <% end %>

</ul>

<% content_for :footer_content do %>
  <div class="fancy-links">
    <%= @homepage['homepage_footer_content'].html_safe %>
  </div>
<% end %>

app/views/partials/_flash_messages.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
	  <div class="alert alert-<%= name.to_s %> alert-dismissable">
	    <%= content_tag :div, msg, :id => "flash_#{name}" %>
	  </div>
	<% end %>
<% end %>

app/views/posts/index.html.erb
<div class="page">
<% if @posts.empty? %>

  <p>No posts yet!</p>

<% else %>

  <div class="posts-list">
    <% @posts.each do |post| %>
      <div class="post-title">
        <h2><%= post.title %></h2>
        <p class="date"><%= post.nice_date %></p>
        <p><%= post.extract %></p>
        <%= link_to "Read More", blog_post_path(post.slug) %>
      </div>
    <% end %>
  </div>

<% end %>
</div>

app/views/posts/show.html.erb
<div class="page">
  <h2 class="post-title"><%= @post.title %></h2>
  <p class="date">Posted on: <%= @post.nice_date %></p>

  <div class="post-content">
    <%= sanitize_html(@post.content) %>
  </div>

  <div class="post-links">
    <%= link_to "Previous post", blog_post_path(@post.prev.slug), class: "prev" if @post.prev.present? %>
    <%= link_to "Next post", blog_post_path(@post.next.slug), class: "next" if @post.next.present? %>
  </div>
</div>